export const  GET_TOP_CUSTOMERS_SUCCESS = " GET_TOP_CUSTOMERS_SUCCESS";
export const   GET_TOP_CUSTOMERS_FAILURE = " GET_TOP_CUSTOMERS_FAILURE";
export const GET_TOP_CUSTOMERS_REQUEST = " GET_TOP_CUSTOMERS_REQUEST";

export const  GET_TOTAL_AMOUNT_SUCCESS = " GET_TOTAL_AMOUNT_SUCCESS";
export const   GET_TOTAL_AMOUNT_FAILURE = " GET_TOTAL_AMOUNT_FAILURE";
export const  GET_TOTAL_AMOUNT_REQUEST = " GET_TOTAL_AMOUNT_REQUEST";

export const  POST_CSV_SUCCESS = "POST_CSV_SUCCESS";
export const  POST_CSV_FAILURE = "POST_CSV_FAILURE";
export const  POST_CSV_REQUEST = "POST_CSV_REQUEST";